import type { BlogPost } from "@/types/index";

const newBlogPost: BlogPost = {
  id: "flutuacao-mergulho-bonito", // This will likely be generated by Supabase, but good for local testing
  title: "Flutuação e Mergulho em Bonito: Uma Experiência Imersiva nas Águas Mais Claras do Brasil",
  slug: "flutuacao-e-mergulho-em-bonito",
  author: "BonitoOn",
  publishedAt: new Date().toISOString(),
  readTime: 10, // Estimated read time in minutes
  image: "/public/aquario_natural/aquario_natural_subaquatica.webp", // Placeholder image
  gallery: [
    "/public/aquario_natural/aquario_natural_peixes.webp",
    "/public/mergulho-com-cilindro-no-rio-da-prata.webp",
    "/public/aquario_natural/aquario_natural_fauna.webp",
  ],
  tags: ["Flutuação", "Mergulho", "Bonito", "Ecoturismo", "Aquário Natural"],
  seoTitle: "Flutuação e Mergulho em Bonito: Águas Cristalinas e Vida Aquática",
  seoDescription: "Descubra a magia da flutuação e do mergulho em Bonito, MS. Explore rios de águas cristalinas e observe a rica fauna e flora aquática, incluindo o famoso Aquário Natural.",
  seoKeywords: ["flutuação bonito", "mergulho bonito", "aquário natural bonito", "ecoturismo bonito", "rios cristalinos bonito"],
  excerpt: `
    <p>Bonito, no Mato Grosso do Sul, é mundialmente conhecido por suas águas cristalinas e a abundância de vida aquática. Entre as atividades mais procuradas, a flutuação e o mergulho oferecem uma imersão inesquecível na natureza exuberante da região.</p>
  `,
  content: `
    <p>Bonito, no Mato Grosso do Sul, é um paraíso ecológico que atrai visitantes de todo o mundo em busca de experiências únicas em meio à natureza. As atividades de flutuação e mergulho se destacam como as mais emblemáticas, proporcionando um contato íntimo e respeitoso com a rica biodiversidade aquática.</p>

    <h2>A Magia da Flutuação: Observação Subaquática em Rios Cristalinos</h2>
    <p>A flutuação é uma experiência acessível e fascinante, ideal para todas as idades. Equipado com máscara, snorkel e colete salva-vidas, você se deixa levar pela correnteza suave de rios e nascentes de águas tão transparentes que a visibilidade é impressionante. É como nadar em um aquário gigante, onde cardumes de peixes coloridos, como piraputangas e dourados, nadam ao seu lado, alheios à sua presença.</p>
    <p>Um dos locais mais emblemáticos para a flutuação é o <strong>Aquário Natural na Nascente do Rio Baía Bonita</strong>. Este santuário aquático é um verdadeiro espetáculo da natureza, abrigando mais de 30 espécies de peixes em um ecossistema perfeitamente preservado. A sensação de flutuar sobre jardins subaquáticos e observar a vida selvagem em seu habitat natural é indescritível e profundamente relaxante.</p>

    <h2>Mergulho com Cilindro: Uma Imersão Mais Profunda</h2>
    <p>Para aqueles que desejam uma experiência ainda mais profunda e emocionante, o mergulho com cilindro em Bonito é uma opção imperdível. Locais como a Lagoa Misteriosa e o Abismo Anhumas oferecem cenários subaquáticos de tirar o fôlego, com formações rochosas impressionantes, cavernas submersas e uma visibilidade que pode ultrapassar os 40 metros.</p>
    <p>O mergulho permite explorar recantos que a flutuação não alcança, revelando um mundo de cores e formas que parecem pertencer a outro planeta. É uma oportunidade de se conectar com a natureza de uma maneira mais intensa, sentindo a leveza e a serenidade do ambiente subaquático.</p>

    <h2>Ecoturismo e Sustentabilidade: Um Compromisso com a Natureza</h2>
    <p>As atividades de flutuação e mergulho em Bonito são cuidadosamente regulamentadas para garantir o mínimo impacto ambiental. Os passeios são realizados em grupos pequenos, com guias especializados que orientam sobre as melhores práticas de conservação. A preocupação com a sustentabilidade é uma prioridade na região, visando preservar esses tesouros naturais para as futuras gerações.</p>
    <p>No entanto, é importante estar ciente das discussões sobre os impactos do turismo na ictiofauna (fauna de peixes). Embora as atividades sejam consideradas de menor impacto, a presença constante de pessoas pode, em alguns casos, alterar o comportamento natural dos peixes. Por isso, a conscientização e o respeito às normas de visitação são fundamentais para garantir que a magia de Bonito permaneça intacta.</p>

    <h2>Planeje Sua Aventura em Bonito</h2>
    <p>Seja flutuando suavemente sobre as águas cristalinas ou explorando as profundezas em um mergulho com cilindro, Bonito oferece experiências que ficarão gravadas na memória. Prepare-se para se maravilhar com a beleza intocada da natureza e viver momentos de pura conexão com o meio ambiente.</p>
    <p>Venha descobrir por que Bonito é considerado um dos melhores destinos de ecoturismo do mundo!</p>
  `,
};

export default newBlogPost;