/**
 * Faixas etárias de criança por passeio, extraídas do tarifário oficial (tarifariobonitoon.com.br).
 * Gerado via: node scripts/sync-child-ages.mjs
 *
 * childMax: null = "a partir de childMin anos"
 */
import type { ChildAgeAges } from "@/lib/child-age-parser"

export const DEFAULT_CHILD_AGES: ChildAgeAges = { childMin: 5, childMax: 12 }

export const TOUR_CHILD_AGE_BY_SLUG: Record<string, ChildAgeAges> = {
  "abismo-anhumas": { childMin: 5, childMax: 12 },
  "aquario-natural": { childMin: 5, childMax: 12 },
  "balneario-cachoeiras-serra-da-bodoquena-com-almoco": { childMin: 6, childMax: null },
  "balneario-do-sol": { childMin: 5, childMax: 11 },
  "balneario-ecopark-porto-da-ilha": { childMin: 5, childMax: 11 },
  "balneario-estrela-do-formoso": { childMin: 5, childMax: 12 },
  "balneario-jardim-ecopark": { childMin: 5, childMax: 12 },
  "balneario-municipal": { childMin: 5, childMax: 11 },
  "balneario-nascente-azul": { childMin: 5, childMax: 11 },
  "barco-eletrico-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
  "barra-do-sucuri": { childMin: 5, childMax: 12 },
  "bike-boat-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
  "bio-park": { childMin: 5, childMax: 12 },
  "boca-da-onca-buraco-do-macaco": { childMin: 7, childMax: 11 },
  "boca-da-onca-rapel-trilha-adventure": { childMin: 7, childMax: 11 },
  "boca-da-onca-trilha-adventure": { childMin: 7, childMax: 11 },
  "boca-da-onca-trilha-adventure-1": { childMin: 7, childMax: 11 },
  "boca-da-onca-trilha-discovery": { childMin: 7, childMax: 11 },
  "boia-cross-cabanas": { childMin: 5, childMax: 11 },
  "boia-cross-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
  "bonito-passeio-de-bote-no-ilha-bonita": { childMin: 5, childMax: 11 },
  "bosque-das-aguas": { childMin: 5, childMax: 12 },
  "buraco-das-araras": { childMin: 5, childMax: 12 },
  "cabanas-arvorismo": { childMin: 5, childMax: 11 },
  "cachoeiras-rio-do-peixe": { childMin: 6, childMax: 12 },
  "cachoeiras-serra-da-bodoquena-com-almoco": { childMin: 6, childMax: 11 },
  "canions-do-salobra": { childMin: 8, childMax: null },
  "cavalgada-estancia-mimosa": { childMin: 6, childMax: 11 },
  "cavalgada-parque-ecologico-rio-formoso": { childMin: 5, childMax: 12 },
  "cavalgada-recanto-do-peao": { childMin: 5, childMax: 12 },
  "cavalgada-rio-da-prata": { childMin: 5, childMax: 12 },
  "combo-bote-ou-combo-duck-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
  "eco-serrana": { childMin: 6, childMax: 11 },
  "eco-serrana-trilhas-e-cachoeiras-com-almoco": { childMin: 6, childMax: 11 },
  "estancia-mimosa": { childMin: 6, childMax: 11 },
  "fazenda-ceita-core": { childMin: 5, childMax: 12 },
  "fazenda-san-francisco": { childMin: 5, childMax: 12 },
  "flutuacao-abismo-anhumas": { childMin: 5, childMax: 12 },
  "flutuacao-praia-da-figueira": { childMin: 5, childMax: 12 },
  "formoso-adventure-tirolesa-arvorismo": { childMin: 5, childMax: 12 },
  "gruta-da-catedral-antiga-gruta-sao-mateus": { childMin: 5, childMax: 12 },
  "gruta-de-sao-miguel": { childMin: 5, childMax: 12 },
  "gruta-do-lago-azul": { childMin: 6, childMax: null },
  "gruta-do-mimoso": { childMin: 5, childMax: 12 },
  "lagoa-misteriosa": { childMin: 5, childMax: 12 },
  "lobo-guara-bike-adventure-bike-tour-no-rio-da-prata": { childMin: 5, childMax: 12 },
  "mergulho-com-cilindro-abismo-anhumas": { childMin: 5, childMax: 12 },
  "mergulho-com-cilindro-discovery-porto-da-ilha": { childMin: 5, childMax: 11 },
  "mergulho-com-cilindro-gruta-do-mimoso": { childMin: 5, childMax: 12 },
  "mergulho-com-cilindro-lagoa-misteriosa": { childMin: 5, childMax: 12 },
  "mergulho-com-cilindro-no-rio-da-prata": { childMin: 5, childMax: 12 },
  "nascente-azul-combo-adventure": { childMin: 5, childMax: 12 },
  "nascente-azul-flutuacao-com-balneario": { childMin: 5, childMax: 12 },
  "nascente-azul-flutuacao-com-balneario-1": { childMin: 5, childMax: 12 },
  "observacao-de-aves-balneario-no-estrela-do-formoso": { childMin: 5, childMax: 12 },
  "pantanal-experiencia": { childMin: 5, childMax: 12 },
  "parque-das-cachoeiras": { childMin: 6, childMax: 11 },
  "parque-ecologico-boia-cross": { childMin: 5, childMax: 12 },
  "passaporte-eco-park-porto-da-ilha-boia-stand-up": { childMin: 5, childMax: 11 },
  "passeio-de-bote-no-porto-da-ilha": { childMin: 5, childMax: 11 },
  "passeio-de-duck-no-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
  "praia-da-figueira": { childMin: 5, childMax: 12 },
  "projeto-jiboia": { childMin: 5, childMax: 12 },
  "projeto-salobra-passeio-encontro-das-aguas": { childMin: 5, childMax: 12 },
  "quadriciclo-balneario-no-estrela-do-formoso": { childMin: 6, childMax: null },
  "quadriciclo-rotta-zagaia": { childMin: 6, childMax: null },
  "quadriciclo-serra-da-bodoquena": { childMin: 6, childMax: null },
  "quadriciclo-trilha-boiadeira": { childMin: 6, childMax: null },
  "refugio-da-barra": { childMin: 5, childMax: 12 },
  "rio-azul-fervedouro": { childMin: 5, childMax: 12 },
  "rio-da-prata": { childMin: 5, childMax: 12 },
  "rio-sucuri": { childMin: 4, childMax: null },
  "rota-aventura": { childMin: 5, childMax: 12 },
  "stand-up-paddle-eco-park-porto-da-ilha": { childMin: 5, childMax: 11 },
}
